server:
  port: 8091

spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

logging:
  level:
    root: INFO

management:
  endpoint:
    gateway:
      enabled: true
    health: true
  endpoints:
    web:
      base-path: /mgm
      exposure:
        include: ["info", "health", "gateway"]